image: node:12.18.2
pipelines:
  branches:
    master:
      - step:
          deployment: production
          caches:
            - node
          script:
            - npm install -g firebase-tools
            - cd functions/ && npm install && firebase deploy --token=$FIREBASE_TOKEN --project $FIREBASE_PROJECT --non-interactive
